apiVersion: v1
kind: Service
metadata: 
  name: kubeapp-consumer-service
  namespace: kubeapp
spec:
  selector:
    app: kubeapp-consumer
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 9081
    targetPort: 9081