apiVersion: v1
kind: Service
metadata: 
  name: kubeapp-app-service
  namespace: kubeapp
spec:
  selector:
    app: kubeapp-app
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 9080
    targetPort: 9080