apiVersion: v1
kind: ConfigMap
metadata: 
  name: kubeapp-mongodb-initdb-configmap
  namespace: kubeapp
data:
  kubeapp.js: |
    print("Begin Init Script.");
    db = db.getSiblingDB('kubeapp');
    db.createUser({
      user: 'kubeappuser',
      pwd: 'kubeapppass',
      roles: [{ role: 'readWrite', db:'kubeapp'}]
    });
    print("DONE.");
