apiVersion: v1
kind: Service
metadata: 
  name: kubeapp-mongodb-service
  labels:
    name: kubeapp-mongodb
  namespace: kubeapp
spec:
  selector:
    app: kubeapp-mongodb
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017